//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adicciones
    {
        public Adicciones()
        {
            this.Adiccion_Cliente = new HashSet<Adiccion_Cliente>();
        }
    
        public int Id_Adiccion { get; set; }
        public string Nombre { get; set; }
        public int Codigo { get; set; }
    
        public virtual ICollection<Adiccion_Cliente> Adiccion_Cliente { get; set; }
    }
}
