//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adiccion_Cliente
    {
        public int Id { get; set; }
        public int Id_Adiccion { get; set; }
        public int Id_Cliente { get; set; }
    
        public virtual Adicciones Adicciones { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
