//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cobertura_de_poliza
    {
        public Cobertura_de_poliza()
        {
            this.Registro_Polizas = new HashSet<Registro_Polizas>();
        }
    
        public int Id_Cobertura { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public double Porcentaje { get; set; }
    
        public virtual ICollection<Registro_Polizas> Registro_Polizas { get; set; }
    }
}
