//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cobertura_de_poliza
    {
        public Cobertura_de_poliza()
        {
            this.Registro_Polizas = new HashSet<Registro_Polizas>();
        }
    
        public int Id_Cobertura { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public double Porcentaje { get; set; }
    
        public virtual ICollection<Registro_Polizas> Registro_Polizas { get; set; }
    }
}
