//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro_Polizas
    {
        public int Id_Poliza { get; set; }
        public int Id_Cobertura { get; set; }
        public int Id_Cliente { get; set; }
        public decimal Monto_Asegurado { get; set; }
        public double Porcentaje_Cobertura { get; set; }
        public int Numero_Adicciones { get; set; }
        public decimal Monto_Adicciones { get; set; }
        public decimal Prima_Antes_Impuestos { get; set; }
        public decimal Impuestos { get; set; }
        public decimal Prima_Final { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Cobertura_de_poliza Cobertura_de_poliza { get; set; }
    }
}
