
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Proyecto.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Rol
{

    public Rol()
    {

        this.Usuarios_Sistema = new HashSet<Usuarios_Sistema>();

    }


    public int Id { get; set; }

    public string Nombre { get; set; }



    public virtual ICollection<Usuarios_Sistema> Usuarios_Sistema { get; set; }

}

}
